server:
  port: 10000
spring:
  application:
    name: ts-front #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer‐ip‐address: true
zuul:
  routes:
    ts-base:              #活动
      path: /base/**             #配置请求URL的请求规则
      serviceId: ts-base  #指定Eureka注册中心中的服务id
    ts-user:              #活动
      path: /user/**             #配置请求URL的请求规则
      serviceId: ts-user
  host:
    socket-timeout-millis: 3000 #指定Eureka注册中心中的服务id
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000

