server: 
  port: 9008
spring: 
  application:  
    name: ts-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.22:3306/tensquare_user?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.8.22
  rabbitmq:
    host: 192.168.8.22

