server: 
  port: 9008
spring: 
  application:  
    name: ts-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://35.221.248.16/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 35.221.248.16
  rabbitmq:
    host: 192.168.8.22
jwt:
  config:
    key: jiao
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
